version: 1.0

jobs:
  build:
    working_directory: ~/simpleOS
    docker:
      - image: cimg/rust:1.50.0
        environment:
          DISPLAY: ":99"
    steps: 
      - run: sudo apt update
      - run: sudo apt install libvirt-daemon-system
      - run: sudo systemctl enable libvirtd
      - run: sudo systemctl start libvirtd
      - run: sudo apt install qemu-kvm
      - checkout
      - run: rustup override set nightly
      - run: cargo --version
      - run: rustc --version
      - run: rustup component add rust-src
      - run: rustup component add llvm-tools-preview
      - run: cargo install bootimage
      - run: cargo bootimage
      - run:
          name: Tests
          command: "cargo test"
