version: 1.0

jobs:
  build:
    working_directory: ~/simpleOS
    docker:
      - image: cimg/rust:1.50.0
        environment:
          DISPLAY: ":99"
    steps: 
      - checkout
      - run: rustup override set nightly
      - run: cargo --version
      - run: rustc --version
      - run: rustup component add rust-src
      - run: rustup component add llvm-tools-preview
      - run:
          name: Tests
          command: "cargo test"
