version: 2.1

jobs:
  build:
    working_directory: ~/simpleOS
    docker:
      - image: rust
    steps:
      - run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - checkout
      - run: rustup override set nightly
      - run: cargo --version
      - run: rustc --version
      - run: rustup component add rust-src
      - run: rustup component add llvm-tools-preview
      - run: cargo install bootimage
      - run: cargo bootimage
      - run:
          name: Tests
          command: "cargo test"
